# Generated by Django 4.1.4 on 2023-01-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0002_subjects_delete_english'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
