# Generated by Django 4.1.4 on 2023-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0007_course_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_credits',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
