# Generated by Django 4.1.4 on 2023-01-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0009_alter_course_credit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='total_credits',
        ),
        migrations.AddField(
            model_name='subject',
            name='user_credits',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
