# Generated by Django 4.1.4 on 2023-01-24 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgrad_app', '0011_course_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='owner',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCredits', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('englishCredits', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('mathCredits', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('scienceCredits', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('socialStudiesCredits', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
