# Generated by Django 4.1.4 on 2023-01-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0012_rename_owner_course_student_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
