# Generated by Django 4.1.4 on 2023-01-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgrad_app', '0013_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='englishCredits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mathCredits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scienceCredits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='socialStudiesCredits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
