# Generated by Django 4.1.4 on 2023-01-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0014_remove_student_englishcredits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
