# Generated by Django 4.1.4 on 2023-01-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0015_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='totalCredits',
        ),
    ]
