# Generated by Django 4.1.4 on 2023-01-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgrad_app', '0016_remove_student_totalcredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='totalCredits',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
